### ISSUE TITLE
En perfil de otro usuario salen mis listas

### ISSUE THREAD

**Issue by daniihc16** [UNIZAR-30226-2024-03/Mobile#18]
He buscado Lucas en el buscador, he entrado en el perfil Lucas Cauhé (estaría bien poner el @nombreUsuario para identificar cuál es) y al entrar en su perfil me aparecen mis listas públicas en lugar de las suyas
@Str1ien

**Comment by daniihc16** [comment]
PD: El reproductor y la pag de la lista son muy feos
PD2: En la pag de usuario el reproductor desaparece, está raro

**Comment by Str1ien** [comment]
Solved
