### ISSUE TITLE
Diseño

### ISSUE THREAD

**Issue by daniihc16** [UNIZAR-30226-2024-03/Mobile#22]
En la pag de explorar los audios que tienen el nombre más largo que la imagen no aparecen con nombrelargoaud....
@alvdef

**Comment by daniihc16** [comment]
Las opciones de los tres puntos de un audio son demasiado pequeñas

**Comment by daniihc16** [comment]
La fecha de ultima modificación del audio no está centrada al mismo nivel en todos los audios,  hace zigzag

**Comment by daniihc16** [comment]
Al buscar un usuario no sale su nombre usuario, que es lo que realmente es único y por lo que se debe buscar un usuario para diferenciarlo de otro

Hay 3 Lucas

**Comment by daniihc16** [comment]
La descripción de la playlist no se ve

**Comment by alvdef** [comment]
solucionado lo del nombre audio

**Comment by daniihc16** [comment]
Las fotos de las listas se ven mal, están escachadas

**Comment by alvdef** [comment]
<img width="290" alt="Screenshot 2024-05-14 at 20 37 58" src="https://github.com/UNIZAR-30226-2024-03/Mobile/assets/97856570/00239a48-2f25-4ed7-be0c-58c518c97758">
limitar solape en movable list

**Comment by Str1ien** [comment]
en la pagina de buscar si la lista es larga se solapa con el trackplayer

**Comment by Str1ien** [comment]
> limitar solape en movable list

añadir width a common_text en SongPeFromAudoData o similares (cuidado con como rompe el flex)

**Comment by alvdef** [comment]
width en trackplayer. centrar titulo?

**Comment by Str1ien** [comment]
en el texto que se quiera limitar

**Comment by daniihc16** [comment]
Rediseño de la lista: foto a la izquierda que se vea entera
A la derecha de eso el título y lo que quepa de descripción, debajo de eso los botones de compartir, colaboradores y shuffle, y debajo de ellos el botón de play

**Comment by daniihc16** [comment]
Rediseño del reproductor:
![Screenshot_2024-05-15-16-46-18-285_com.spoti.plus.jpg](https://github.com/UNIZAR-30226-2024-03/Mobile/assets/90794912/21ce5a84-582b-4b69-9ac3-3cb5c82bbe69)

**Comment by daniihc16** [comment]
No poner las fechas en los audios, solo la duración,

**Comment by alvdef** [comment]
> La duración de las canciones si el segundo solo tiene una cifra hay que ponerle un 0 4:05 en lugar de 4:5

solved
