### ISSUE TITLE
He seguido a lucas y no me aparece en la pestaña de siguiendo

### ISSUE THREAD

**Issue by daniihc16** [UNIZAR-30226-2024-03/Mobile#26]

**Comment by lucas-cauhe** [comment]
@Str1ien
Pasos para reproducir: 
- Entras en la pantalla de amigos 
- Vas a la de buscar y entras en un usuario y lo sigues
- vuelves a la de amigos y no aparece

No estás rerenderizando amigos cuando sigues/dejas de seguir a un usuario

**Comment by Str1ien** [comment]
solved
